### PR TITLE
adding openssl support

### PR DESCRIPTION
**Pull request by igormcoelho**

### CODE REVIEW

**Comment by igormcoelho** [comment]
@shargon , `make -f Makefile-openssl` should already be making in openssl :)

**Comment by shargon** [comment]
I will test it ! :) thanks !!

**Comment by igormcoelho** [comment]
Ok Shargon, now windows build is also included for you :) struggled to make this thing on linux...

**Comment by igormcoelho** [comment]
Houston, we have a problem! hahahah Shargonius my friend, these guys at openssl are crazy... I had tested on linux version openssl-1.1.0, which works ok with your Crypto codes. However, it failed tests when cross compiling to windows, so I switched to openssl-1.0.2-LTS, which indeed passed the windows tests, but I just realized it seems to lack function `ECDSA_SIG_set0`, that you use.

```
/** Setter for r and s fields of ECDSA_SIG
 *  \param  sig  pointer to ECDSA_SIG pointer
 *  \param  r    pointer to BIGNUM for r (may be NULL)
 *  \param  s    pointer to BIGNUM for s (may be NULL)
 */
int ECDSA_SIG_set0(ECDSA_SIG *sig, BIGNUM *r, BIGNUM *s);
```

Some good soul implemented it only in 2016, https://github.com/openssl/openssl/pull/1193, and it came to 1.1.0, but not 1.0.2 lts (which does not make any sense for me!). Anyway, I will try to provide a windows build for you of openssl-1.1.0, even not fully passing tests, so you can start using it, while we figure it out how to deal with the Dubious tests.

**Comment by shargon** [comment]
Thansk so much!

**Comment by shargon** [comment]
Libressl 2.7.4 updated, please rebase the PR :)

**Comment by igormcoelho** [comment]
How do I rebase the commit?
I'm now struggling with windows, decided to build directly here!! This tutorial is good: https://stackoverflow.com/questions/45494630/how-to-build-openssl-on-windows-with-visual-studio-2017#45495686
Just need to install perl and nasm, open visual studio 64 bits console, `perl Configure VC-WIN64A`, `nmake`. It finally works (the .lib), but on runtime it depens on libcrypto-1_1-x64.dll... should it be fully static?

**Comment by shargon** [comment]
Could you add the version to the folders, and choose only one openssl version xD

**Comment by igormcoelho** [comment]
Ok @shargon , now it's good to go! openssl-1.1.0i is the perfect version, for both linux and windows. Time to test! :)

**Comment by shargon** [comment]
With openssl

image

With libressl

image

**OpenSSL WIN**

**Comment by vncoelho** [comment]
Incredible work, my friends. Congratulations to the great insight from both of you.
Thanks for the opportunity for watching such great minds.

**Comment by igormcoelho** [comment]
I told you @shargon! now you officially owe me some beers ;)

**Comment by shargon** [comment]
Deserved beers!

**Comment by shargon** [comment]
Please wait for @belane , he will change the name of the project for prepare for nuget package, then we need to solve the conflicts here and change to OpenSSL

**Comment by igormcoelho** [comment]
Ok Shargon, I guess that's it :)

**Comment by shargon** [comment]
There are conflicts ...

**Comment by igormcoelho** [comment]
How is it broken Shargon? I don't understand where these conflicts come from hahaha anyway, I'll try to merge directly to your development branch.

**Pull request closed without merging**
